name: most_schema_parser
description: Highly customizable JSON Schema object model mapper.
version: 0.0.2
repository: https://github.com/MOST-Innovation-Labs/most_key_value_editor

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  json_schema: ^5.1.3

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
